export const fonts = [
  'Aller_Bd',
  'AllerDisplay',
  'ArmWrestler',
  'batmanforeveralternate',
  'BLACKR',
  'BOYCOTT_',
  'COLLEGEC',
  'DESTROY_',
  'edo',
  'GESSO___',
  'JUICE_Light',
  'old_stamper',
  'OSP-DIN',
  'ostrich-regular',
  'Santana',
  'Ubuntu-Title',
  'Bellota-Regular',
  'Blueberry Regular',
  'BubblegumSans-Regular',
  'BunnyFunny',
  'Kraash',
  'Candyshop',
  'CevicheOne-Regular',
  'clutchee',
  'Farsan-Regular',
  'FasterOne-Regular',
  'FirecatMedium',
  'Kraash Black',
  'GrinchedRegular',
  'handlee-regular',
  'JosefinSans-Bold',
  'KaushanScript-Regular',
  'LondrinaSolid-Regular',
  'NosiferCaps-Regular',
  'Oleander Cakes',
  'orbitron-medium',
  'Paprika-Regular',
  'Pokemon Solid',
  'Sansation-Light',
  'Sansita-Regular',
  'SofadiOne-Regular',
  'Spirax-Regular',
  'Stella Demo',
  'Subscribe',
  'Subspace Bold',
  'teko-medium',
  'TradeWinds-Regular',
  'Vanilla',
  'xenophone'
]
